teams:
  - name: lf-staff
    maintainers:
      - christinaharter
      - hartm
      - oqs-bot
      - ryjones
      - abhvious
      - matteo-frigo
      - ask77nl
    members: []

repositories:
  - name: .github
    teams:
      lf-staff: maintain
    visibility: public
  - name: tsc
    teams:
      lf-staff: maintain
    visibility: public
