teams:
  - name: lf-staff
    maintainers:
      - christinaharter
      - hartm
      - oqs-bot
      - ryjones
    members: []
  - name: longfellow-developers
    maintainers:
      - abhvious
    members:
      - albertoleon7794
      - andrea-dintino
      - arnab-roy
      - danielksan81
      - gtank
      - himazawa
      - Imperiopolis
      - kunallimaye
      - MarcIlunga
      - Roee-87
      - siriscac
      - SuperHex
      - TheCoryBarker
      - therealyingtong
      - tob-joe
      - vincentcourson
      - WaltzOfWhispers
      - zoracon
  - name: longfellow-maintainers
    maintainers:
      - abhvious
    members:
      - ask77nl
      - matteo-frigo
repositories:
  - name: .github
    teams:
      lf-staff: maintain
      longfellow-maintainers: maintain
    visibility: public
  - name: longfellow-zk
    teams:
      lf-staff: maintain
      longfellow-maintainers: maintain
      longfellow-developers: write
    visibility: public
  - name: tsc
    teams:
      lf-staff: maintain
      longfellow-maintainers: maintain
    visibility: public
